# Generated by Django 2.0.4 on 2018-06-06 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0002_auto_20180606_1630'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='tags',
            new_name='tag',
        ),
    ]
